const SEED_PROJECTS = [
  // ==========================================
  // TECH & SCIENCE (3 Projects)
  // ==========================================
  {
    id: '1',
    title: 'Smart Solar-Powered Desk Lamp',
    description: 'Designed a low-cost study lamp using a small solar panel, a rechargeable AA battery, and a light-dependent resistor (LDR) that automatically turns on when the room gets dark.',
    category: 'Tech & Science',
    tags: ['Solar Energy', 'Electronics', 'Green Tech'],
    coverImage: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Aditya Krishna',
    school: 'LIPS',
    grade: 'Grade 9',
    likes: 184,
    views: 920,
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    title: 'Plant Moisture Indicator Device',
    description: 'Built a simple soil diagnostic tool using an Arduino Uno and a basic moisture sensor probe. The indicator lights up a red LED when a household potted plant needs watering.',
    category: 'Tech & Science',
    tags: ['Arduino', 'Botany', 'Sensors'],
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Fathima Zara',
    school: 'LIPS',
    grade: 'Grade 11',
    likes: 245,
    views: 1210,
    createdAt: '2025-02-10',
  },
  {
    id: '3',
    title: 'Homemade Eco-Friendly Water Filter',
    description: 'Tested filtration rates using an organic layered setup consisting of charcoal, fine sand, coarse gravel, and cotton to purify muddy rainwater for garden irrigation.',
    category: 'Tech & Science',
    tags: ['Environment', 'Chemistry', 'Filtration'],
    coverImage: 'https://images.unsplash.com/photo-1617155093730-a8bf47be792d?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1617155093730-a8bf47be792d?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Meenakshi Suresh',
    school: 'LIPS',
    grade: 'Grade 8',
    likes: 198,
    views: 840,
    createdAt: '2025-03-02',
  },

  // ==========================================
  // ARTS & MUSIC (3 Projects)
  // ==========================================
  {
    id: '4',
    title: 'First Prize in Solo Violin Classical Category',
    description: 'Awarded the highly competitive A-Grade first place prize in the Carnatic Solo Violin division at the annual Revenue District Youth Arts Festival.',
    category: 'Arts & Music',
    tags: ['Violin', 'Carnatic', 'Festival'],
    coverImage: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Sreelakshmi R',
    school: 'LIPS',
    grade: 'Grade 12',
    likes: 312,
    views: 1680,
    createdAt: '2025-02-18',
  },
  {
    id: '5',
    title: 'Traditional Mural Painting Showcase',
    description: 'Won the top honors in the spot-painting exhibition category by recreating a complex, traditional Kerala-style temple mural design using acrylic mediums.',
    category: 'Arts & Music',
    tags: ['Mural', 'Painting', 'Traditional Arts'],
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Nanditha Pillai',
    school: 'LIPS',
    grade: 'Grade 10',
    likes: 421,
    views: 1980,
    createdAt: '2025-03-11',
  },
  {
    id: '6',
    title: 'Light Music Vocal Performance Recording',
    description: 'Secured an A-Grade ranking in the Malayalam Light Music vocal performance division at the regional level, showcasing control over rhythm and semi-classical melodies.',
    category: 'Arts & Music',
    tags: ['Vocal', 'Light Music', 'Performance'],
    coverImage: 'https://images.unsplash.com/photo-1516280440614-37939bbacd6a?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1516280440614-37939bbacd6a?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Madhav Swaroop',
    school: 'LIPS',
    grade: 'Grade 11',
    likes: 289,
    views: 1150,
    createdAt: '2025-01-28',
  },

  // ==========================================
  // SPORTS & GAMES (3 Projects)
  // ==========================================
  {
    id: '7',
    title: 'State-Level Kho-Kho Championship Glory',
    description: 'Represented our school and captained the regional sub-district squad to secure the gold medal at the Kerala State Level Kho-Kho Championship tournament.',
    category: 'Sports & Games',
    tags: ['Kho-Kho', 'Championship', 'Athletics'],
    coverImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Arjun Menon',
    school: 'LIPS',
    grade: 'Grade 11',
    likes: 532,
    views: 2450,
    createdAt: '2025-01-20',
  },
  {
    id: '8',
    title: 'Sub-District Badminton Singles Runner-Up',
    description: 'Fought through five continuous elimination rounds to secure the silver medal/runner-up trophy in the Under-17 boys singles category at the sub-district tournament.',
    category: 'Sports & Games',
    tags: ['Badminton', 'Singles', 'Tournament'],
    coverImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Rohan Das',
    school: 'LIPS',
    grade: 'Grade 12',
    likes: 195,
    views: 940,
    createdAt: '2025-02-05',
  },
  {
    id: '9',
    title: 'Annual Sports Meet Inter-House Chess Champ',
    description: 'Maintained an undefeated record through 7 matches of swiss-system pairings to claim the individual gold medal in the senior chess championship division.',
    category: 'Sports & Games',
    tags: ['Chess', 'Strategy', 'Indoor Games'],
    coverImage: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=60',
    images: ['https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=60'],
    authorName: 'Ananya Prabhu',
    school: 'LIPS',
    grade: 'Grade 10',
    likes: 167,
    views: 780,
    createdAt: '2025-03-05',
  }
];

export default SEED_PROJECTS;